## DSM 2022 - Assignment_1  - Theophilus Yao Dortumor

In [2]:
# importing libraries 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
#import random.seed(123)
import warnings
#import warnings.filterwarning('IGNORE')

## Question 1

In [3]:
# calculating overtime pay per week

# standard inputs for calculation
std_hrs_per_week = 40 
wage_per_hour = 45
overtime_wage_per_hour = 50

# creating user inputs required for computing user's overtime
total_hrs_per_week = float(input('Enter the your total number of hours per week: '))
base_salary = float(input('Enter your base salary per week: $'))

# function to compute the overtime pay
def overtime (total_hrs_per_week, std_hrs_per_week):
    overtime_hours = total_hrs_per_week - std_hrs_per_week
    overtime_pay = overtime_hours*overtime_wage_per_hour
    print('Your overtime pay for the week is: ${:.2f}'.format(overtime_pay))


overtime(total_hrs_per_week, std_hrs_per_week)

Enter the your total number of hours per week: 50
Enter your base salary per week: $1800
Your overtime pay for the week is: $500.00


## Question 2

In [4]:
#creating list of ten values with user inputs 

mylist1 = []

while len(mylist1) < 10:
    num = float(input('enter your number '))
    mylist1.append(num)
    mylist1 = sorted(mylist1)
    
print('Final list ', mylist1)

enter your number 25
enter your number 23
enter your number 10
enter your number 14
enter your number 11
enter your number 8
enter your number 6
enter your number 2
enter your number 4
enter your number 21
Final list  [2.0, 4.0, 6.0, 8.0, 10.0, 11.0, 14.0, 21.0, 23.0, 25.0]


In [5]:
# recreating list using list comprehension
mylist2 = [item for item in mylist1]
sorted(mylist2)

[2.0, 4.0, 6.0, 8.0, 10.0, 11.0, 14.0, 21.0, 23.0, 25.0]

## Question 3

In [6]:
# creating a new dictionary 
my_dict1 = {'School':'MTSU','Textbooks':14,'Level':'Elementary','Hobby':'Dancing', 'Height':'4.5inch', 'Food':'Amala'}
print('Original dictionary')
print('=======================================')
print(my_dict1)


#updating dictionary with my credentials
my_credential = {'School':'UCC', 'Textbooks': 16, 'Level': 'Graduate', 'Hobby':'Reading', 'Height':'4.2inch', 'Food':'Banku'}
my_dict1.update(my_credential)
print()
print()
print('Dictionary updated with my credentials')
print('=======================================')
print(my_dict1)

#updating dictionary with new pair
new_pair = {'Is_location_USA': True, 'Is_Married': 'No'}
my_dict1.update(new_pair)
print()
print()
print('Dictionary updated with new key-value pairs')
print('============================================')
print(my_dict1)

# removing 'Hobby':'Dancing' key-value pair
my_dict1.pop('Hobby')
print()
print()
print('Dictionary after removing Hobby')
print('============================================')
print(my_dict1)

#deleting last entry of updated dictionary
my_dict1.popitem()
print()
print()
print('Dictionary deleting last entry')
print('============================================')
print(my_dict1)

Original dictionary
{'School': 'MTSU', 'Textbooks': 14, 'Level': 'Elementary', 'Hobby': 'Dancing', 'Height': '4.5inch', 'Food': 'Amala'}


Dictionary updated with my credentials
{'School': 'UCC', 'Textbooks': 16, 'Level': 'Graduate', 'Hobby': 'Reading', 'Height': '4.2inch', 'Food': 'Banku'}


Dictionary updated with new key-value pairs
{'School': 'UCC', 'Textbooks': 16, 'Level': 'Graduate', 'Hobby': 'Reading', 'Height': '4.2inch', 'Food': 'Banku', 'Is_location_USA': True, 'Is_Married': 'No'}


Dictionary after removing Hobby
{'School': 'UCC', 'Textbooks': 16, 'Level': 'Graduate', 'Height': '4.2inch', 'Food': 'Banku', 'Is_location_USA': True, 'Is_Married': 'No'}


Dictionary deleting last entry
{'School': 'UCC', 'Textbooks': 16, 'Level': 'Graduate', 'Height': '4.2inch', 'Food': 'Banku', 'Is_location_USA': True}


## Question 4



In [7]:
# creating a 20 by 11 array of ones
myarray1 = np.ones((20,11), dtype = float)
myarray1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.

In [8]:
# multiplying myarray1 by a scalar of 0.5
myarray1=myarray1*0.5
myarray1

array([[0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.

In [9]:
# updating the 6th row with 10.5
myarray1[5, :] = 10.5
myarray1

array([[ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5],
       [ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,

In [10]:
#updaating the 7th row with 11.5
myarray1[6,:] = 11.5
myarray1

array([[ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5],
       [11.5, 11.5, 11.5, 11.5, 11.5, 11.5, 11.5, 11.5, 11.5, 11.5, 11.5],
       [ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,

In [11]:
# updating the first row with 9.5
myarray1[:, 0] = 9.5
myarray1

array([[ 9.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 9.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 9.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 9.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 9.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 9.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5],
       [ 9.5, 11.5, 11.5, 11.5, 11.5, 11.5, 11.5, 11.5, 11.5, 11.5, 11.5],
       [ 9.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 9.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 9.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 9.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 9.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 9.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 9.5,  0.5,  0.5,

In [12]:
# slicing 5th to 11th row
myarray1[4:11, :]

array([[ 9.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 9.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5],
       [ 9.5, 11.5, 11.5, 11.5, 11.5, 11.5, 11.5, 11.5, 11.5, 11.5, 11.5],
       [ 9.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 9.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 9.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 9.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5]])

In [13]:
# slicing 6th to 9th column
myarray1[:, 5:9]


array([[ 0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5],
       [10.5, 10.5, 10.5, 10.5],
       [11.5, 11.5, 11.5, 11.5],
       [ 0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5]])

In [14]:
# Merge the 6th column with 8th column using np.hstack
np.hstack([myarray1[:, 5],myarray1[:, 7]])

array([ 0.5,  0.5,  0.5,  0.5,  0.5, 10.5, 11.5,  0.5,  0.5,  0.5,  0.5,
        0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,
        0.5,  0.5,  0.5, 10.5, 11.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,
        0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5])

In [15]:
# Merge the 5th column with 10th column using np.vstack
np.vstack([myarray1[:, 4],myarray1[:, 9]])

array([[ 0.5,  0.5,  0.5,  0.5,  0.5, 10.5, 11.5,  0.5,  0.5,  0.5,  0.5,
         0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5,  0.5, 10.5, 11.5,  0.5,  0.5,  0.5,  0.5,
         0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5]])

Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement XeLaTex (from versions: none)
ERROR: No matching distribution found for XeLaTex
